# Generated by Django 3.0.7 on 2020-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200702_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.TextField(blank=True, default='', verbose_name='Rating'),
        ),
    ]
