# Generated by Django 3.0.7 on 2020-06-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(choices=[('WM', 'Walmart'), ('KM', 'Kmart')], default='', max_length=25, verbose_name='Supplier')),
                ('username', models.CharField(blank=True, default='', max_length=30, verbose_name='Username')),
                ('email', models.EmailField(default='', max_length=30, verbose_name='Email')),
                ('password', models.CharField(default='', max_length=30, verbose_name='Password')),
                ('is_current_supplier', models.BooleanField(blank=True, default=False, verbose_name='Current Supplier')),
            ],
        ),
    ]
