# Generated by Django 3.0.7 on 2020-06-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplieraccount', '0003_auto_20200611_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieraccount',
            name='supplier',
            field=models.CharField(choices=[('WM', 'Walmart'), ('KM', 'Kmart'), ('SC', 'SamsClub')], default='', max_length=25, verbose_name='Supplier'),
        ),
        migrations.DeleteModel(
            name='UserSupplierAccount',
        ),
    ]
