# Generated by Django 3.0.7 on 2020-06-10 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplieraccount', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Order id')),
                ('quantity', models.CharField(blank=True, default='', max_length=10, verbose_name='Order quantity')),
                ('price', models.CharField(blank=True, default='', max_length=10, verbose_name='Order price')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplieraccount.SupplierAccount', verbose_name='Supplier account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('NOTHING', 'Nothing'), ('OOS', 'Out of stock'), ('SUCCESS', 'Success'), ('WRONG_DATA', 'Product was added with invalid data'), ('WRONG_ITEM', 'Invalid product in cart'), ('ADDING_PROBLEM', 'Problem with adding'), ('WRONG_COUNT', 'This count not availability'), ('IN_PROGRESS', 'In progress...')], default='NOTHING', max_length=50)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_image', models.ImageField(blank=True, null=True, upload_to='status_image')),
                ('tag', models.CharField(blank=True, default='', max_length=100, verbose_name='Tag')),
                ('order_status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.OrderStatus', verbose_name='Order status')),
            ],
        ),
    ]
