# Generated by Django 3.0.7 on 2020-06-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatusimage',
            name='status_image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='status_image'),
        ),
    ]
