# Generated by Django 3.0.7 on 2020-07-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200626_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.TextField(blank=True, default='', verbose_name='Order id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Order price'),
        ),
        migrations.AlterField(
            model_name='orderstatusimage',
            name='tag',
            field=models.TextField(blank=True, default='', verbose_name='Tag'),
        ),
    ]
